# Data Cleaning and Preparation (Data Wrangling)

## Load Dataset :-

In [6]:
# Importing libraries
import pandas as pd
import numpy as np

# Loding dataset
customers = pd.read_csv("D:/Documents/Documents/Data_Analytics/PROJECT/Resume Projects/E-Commerce Customer & Sales Analytics/dataset/customers.csv")
order_items = pd.read_csv("D:/Documents/Documents/Data_Analytics/PROJECT/Resume Projects/E-Commerce Customer & Sales Analytics/dataset/order_items.csv")
orders = pd.read_csv("D:/Documents/Documents/Data_Analytics/PROJECT/Resume Projects/E-Commerce Customer & Sales Analytics/dataset/orders.csv")
products = pd.read_csv("D:/Documents/Documents/Data_Analytics/PROJECT/Resume Projects/E-Commerce Customer & Sales Analytics/dataset/products.csv")

## Data Understanding

In [ ]:
# Displaying Top 5 rows of dataset

In [11]:
customers.head()

   customer_id country signup_date
0            1   Spain  15-05-2023
1            2   Italy  10-02-2023
2            3   Spain  23-10-2023
3            4  France  03-01-2023
4            5   Italy  05-02-2024

In [13]:
order_items.head()

   order_id  product_id  quantity  price
0       508          48         3    108
1       290          18         2     93
2       295          16         2     27
3       451          39         2     54
4       904           4         4    117

In [14]:
orders.head()

   order_id  customer_id  order_date     status
0         1          103  2024-10-31  Completed
1         2          271  2024-10-12  Completed
2         3          107  2024-05-23  Completed
3         4           72  2024-01-19  Completed
4         5          189  2024-01-18  Completed

In [15]:
products.head()

   product_id product_name category
0           1    Product_1     Body
1           2    Product_2     Skin
2           3    Product_3     Hair
3           4    Product_4     Body
4           5    Product_5     Skin

In [ ]:
# Understanding data

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  300 non-null    int64
 1   country      300 non-null    object
 2   signup_date  300 non-null    object
dtypes: int64(1), object(2)
memory usage: 7.2+ KB

In [22]:
customers.shape

(300, 3)

In [17]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    2000 non-null   int64
 1   product_id  2000 non-null   int64
 2   quantity    2000 non-null   int64
 3   price       2000 non-null   int64
dtypes: int64(4)
memory usage: 62.6 KB

In [23]:
order_items.shape

(2000, 4)

In [19]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     1000 non-null   int64
 1   customer_id  1000 non-null   int64
 2   order_date   1000 non-null   object
 3   status       1000 non-null   object
dtypes: int64(2), object(2)
memory usage: 31.4+ KB

In [24]:
orders.shape

(1000, 4)

In [20]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    50 non-null     int64
 1   product_name  50 non-null     object
 2   category      50 non-null     object
dtypes: int64(1), object(2)
memory usage: 1.3+ KB

In [25]:
products.shape

(50, 3)

## Checking Null values

In [28]:
customers.isnull().sum()

customer_id    0
country        0
signup_date    0
dtype: int64

In [29]:
order_items.isnull().sum()

order_id      0
product_id    0
quantity      0
price         0
dtype: int64

In [30]:
orders.isnull().sum()

order_id       0
customer_id    0
order_date     0
status         0
dtype: int64

In [31]:
products.isnull().sum()

product_id      0
product_name    0
category        0
dtype: int64

##### There are no null/missing values in dataset

## Checking Duplicate

In [34]:
customers.duplicated().sum()

np.int64(0)

In [35]:
order_items.duplicated().sum()

np.int64(0)

In [36]:
orders.duplicated().sum()

np.int64(0)

In [37]:
products.duplicated().sum()

np.int64(0)

##### There are no duplicates in dataset

## Fixing Datatypes

In [39]:
# fixing date colunms datatype
customers['signup_date'] = pd.to_datetime(customers['signup_date'])

C:\Users\abhij\AppData\Local\Temp\ipykernel_12268\2100024663.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  customers['signup_date'] = pd.to_datetime(customers['signup_date'])

In [43]:
orders['order_date'] = pd.to_datetime(orders['order_date'])

In [56]:
# creating month column
orders['month'] = orders['order_date'].dt.month_name()

In [61]:
# creating day column
orders['day'] = orders['order_date'].dt.day_name()

In [ ]:
# Checking updated datatypes

In [53]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  300 non-null    int64
 1   country      300 non-null    object
 2   signup_date  300 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 7.2+ KB

In [62]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     1000 non-null   int64
 1   customer_id  1000 non-null   int64
 2   order_date   1000 non-null   datetime64[ns]
 3   status       1000 non-null   object
 4   month        1000 non-null   object
 5   day          1000 non-null   object
dtypes: datetime64[ns](1), int64(2), object(3)
memory usage: 47.0+ KB

## MERGE TABLES

In [63]:
df = orders.merge(
    customers,
    on='customer_id',
    how='left'
)

df = df.merge(
    order_items,
    on='order_id',
    how='left'
)

df = df.merge(
    products,
    on='product_id',
    how='left'
)

In [64]:
df

,order_id,customer_id,order_date,status,month,day,country,signup_date,product_id,quantity,price,product_name,category
0,1,103,2024-10-31,Completed,October,Thursday,Italy,2023-03-22,13.0,4.0,58.0,Product_13,Skin
1,2,271,2024-10-12,Completed,October,Saturday,France,2023-08-29,NaN,NaN,NaN,NaN,NaN
2,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,18.0,1.0,25.0,Product_18,Makeup
3,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,24.0,4.0,41.0,Product_24,Hair
4,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,42.0,2.0,66.0,Product_42,Skin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2134,996,215,2024-05-31,Completed,May,Friday,Germany,2024-02-15,23.0,4.0,13.0,Product_23,Body
2135,997,211,2024-01-19,Completed,January,Friday,Italy,2023-07-16,45.0,5.0,22.0,Product_45,Body
2136,998,32,2024-04-09,Completed,April,Tuesday,Italy,2024-01-02,NaN,NaN,NaN,NaN,NaN
2137,999,158,2024-02-29,Completed,February,Thursday,Italy,2024-01-02,19.0,2.0,18.0,Product_19,Makeup
2138,1000,285,2024-06-15,Completed,June,Saturday,Spain,2023-07-21,33.0,3.0,28.0,Product_33,Hair

In [65]:
df.isnull().sum()

order_id          0
customer_id       0
order_date        0
status            0
month             0
day               0
country           0
signup_date       0
product_id      139
quantity        139
price           139
product_name    139
category        139
dtype: int64

In [ ]:
# We found some null values after merging the tables i.e some orders without products.

In [71]:
# checking which orders are without products
orders_without_items = orders[
    ~orders['order_id'].isin(order_items['order_id'])
]

print(orders_without_items.head())

    order_id  customer_id order_date     status      month       day
1          2          271 2024-10-12  Completed    October  Saturday
8          9          215 2024-07-12  Completed       July    Friday
15        16          294 2024-09-20  Completed  September    Friday
23        24           59 2024-02-24  Completed   February  Saturday
33        34          135 2024-11-23  Cancelled   November  Saturday

In [67]:
# Remove rows without products
df = df.dropna(subset=['product_id'])

In [68]:
df

,order_id,customer_id,order_date,status,month,day,country,signup_date,product_id,quantity,price,product_name,category
0,1,103,2024-10-31,Completed,October,Thursday,Italy,2023-03-22,13.0,4.0,58.0,Product_13,Skin
2,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,18.0,1.0,25.0,Product_18,Makeup
3,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,24.0,4.0,41.0,Product_24,Hair
4,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,42.0,2.0,66.0,Product_42,Skin
5,3,107,2024-05-23,Completed,May,Thursday,Italy,2024-01-05,35.0,5.0,74.0,Product_35,Skin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2133,995,141,2024-02-19,Completed,February,Monday,Germany,2024-05-11,21.0,1.0,12.0,Product_21,Hair
2134,996,215,2024-05-31,Completed,May,Friday,Germany,2024-02-15,23.0,4.0,13.0,Product_23,Body
2135,997,211,2024-01-19,Completed,January,Friday,Italy,2023-07-16,45.0,5.0,22.0,Product_45,Body
2137,999,158,2024-02-29,Completed,February,Thursday,Italy,2024-01-02,19.0,2.0,18.0,Product_19,Makeup
2138,1000,285,2024-06-15,Completed,June,Saturday,Spain,2023-07-21,33.0,3.0,28.0,Product_33,Hair

In [70]:
# Checking Null values
df.isnull().sum()

order_id        0
customer_id     0
order_date      0
status          0
month           0
day             0
country         0
signup_date     0
product_id      0
quantity        0
price           0
product_name    0
category        0
dtype: int64

In [78]:
# Add Revenue column tp table

df['revenue'] = df['quantity']*df['price']

C:\Users\abhij\AppData\Local\Temp\ipykernel_12268\3342418062.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue'] = df['quantity']*df['price']

In [80]:
# Final check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2000 entries, 0 to 2138
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      2000 non-null   int64
 1   customer_id   2000 non-null   int64
 2   order_date    2000 non-null   datetime64[ns]
 3   status        2000 non-null   object
 4   month         2000 non-null   object
 5   day           2000 non-null   object
 6   country       2000 non-null   object
 7   signup_date   2000 non-null   datetime64[ns]
 8   product_id    2000 non-null   float64
 9   quantity      2000 non-null   int64
 10  price         2000 non-null   float64
 11  product_name  2000 non-null   object
 12  category      2000 non-null   object
 13  revenue       2000 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(6)
memory usage: 234.4+ KB

In [82]:
# Export cleaned data

df.to_csv(
    "cleaned_data.csv",
    index=False
)